---
title: "CS7200_final_project_UPDATED"
author: "Sarah, Shira, Dorsa"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(lmerTest)
library(lattice)
```

# Research Questions
1) Is there a difference in ambulation and upright activity in the first half month of March vs second?

2) Does personalized health coaching make a difference in the first half month of March vs second half? (We hope yes)

3) How much does variability is between participants?

``` {r Data Cleaning}
data <- read.csv('data_full.csv')

part_3 <- data %>% 
  drop_na(group) %>% # dropped participants who were not in either control or treatment
  mutate(PARTICIPANT = as.factor(PARTICIPANT),
         ambulation_prop = Ambulation/HOURS_COVERAGE,
         upright_prop = Upright..Other. / HOURS_COVERAGE,
         month = as.factor(format(as.Date(DATE, format="%Y-%m-%d"),"%m")),
         day = as.numeric(format(as.Date(DATE), "%d")),
         year = as.numeric(format(as.Date(DATE), "%y")),
         half = as.factor(case_when(day <= 15 ~ 1, TRUE ~ 2)), # split by 1st and 2nd half of month
         half = as.factor(half)) %>% 
  filter(month == "03") %>% # filter to month of March only
  # note that March data is only 2022, so no need to test normality across two 
  # different years or worry about inappropriately combining 2021 and 2022 data.
  select(PARTICIPANT, group, half, year, upright_prop, ambulation_prop, HOURS_COVERAGE)

# aggregate so there is one value for each participant for each half
part_3_agg <- part_3 %>% 
  group_by(PARTICIPANT, half, group) %>% 
  summarize(mean_upright = mean(upright_prop),
            mean_ambulation = mean(ambulation_prop))

# filter out those that did not contribute to full month
part_3 <- part_3 %>% 
  filter(!PARTICIPANT %in% c('CR21B', 'CR46'))

part_3_agg <- part_3_agg %>% 
  filter(!PARTICIPANT %in% c('CR21B', 'CR46'))

```

```{r Descriptive Stats}
part_trt <- part_3 %>% 
  filter(group == 'Treatment')

part_ctrl <- part_3 %>% 
  filter(group == 'Control')

part_m1 <- part_3 %>% 
  filter(half == 1)

part_m2 <- part_3 %>% 
  filter(half == 2)

part_trt_m1 <- part_trt %>% 
  filter(half == 1)

part_trt_m2 <- part_trt %>% 
  filter(half == 2)

mean_activity_group <- part_3 %>% 
  group_by(group) %>% 
  summarise(mean_upright = mean(upright_prop),
            sd_upright = sd(upright_prop),
            mean_ambulation = mean(ambulation_prop),
            sd_ambulation = sd(ambulation_prop))

mean_activity_half <- part_3 %>% 
  group_by(half) %>% 
  summarise(mean_upright = mean(upright_prop),
            mean_ambulation = mean(ambulation_prop))

# test normality to determine non/parametric data
shapiro.test(part_3$upright_prop) # not normal
shapiro.test(part_3$ambulation_prop) # not normal

# Is there a difference in activity between treatment and control?
wilcox.test(part_trt$upright_prop, part_ctrl$upright_prop) # p-value < 0.05, diff
wilcox.test(part_trt$ambulation_prop, part_ctrl$ambulation_prop) # p-value < 0.05, diff

# Is there a difference in activity between first half and second?
wilcox.test(part_m1$upright_prop, part_m2$upright_prop) # p-value > 0.05, no diff
wilcox.test(part_m1$ambulation_prop, part_m2$ambulation_prop) # p-value < 0.05, diff

# Is there a difference in activity between treatment in first half and treatment in second?
wilcox.test(part_trt_m1$upright_prop, part_trt_m2$upright_prop) # p-value > 0.05, no diff
wilcox.test(part_trt_m1$ambulation_prop, part_trt_m2$ambulation_prop) # p-value > 0.05, no diff

```

```{r Visualizations}
## We should choose what visualizations are most relevant to our story

# for context, graph activity of the entire year treatment vs. control???

# What does the distribution of upright activity look like for each half of the month and by group?
ggplot(part_3, aes(half, upright_prop)) +
  geom_boxplot() +
  facet_wrap(~group)

# What does the distribution of ambulation activity look like for each half of the month and by group?
ggplot(part_3, aes(half, ambulation_prop)) +
  geom_boxplot() +
  facet_wrap(~group)

# What does the distribution of upright activity look like for each participant for each half of the month?
ggplot(part_3, aes(PARTICIPANT, upright_prop, color = PARTICIPANT)) +
  geom_boxplot()

# What does the distribution of ambulation activity look like for each participant for each half of the month?
ggplot(part_3, aes(PARTICIPANT, ambulation_prop, color = PARTICIPANT)) +
  geom_boxplot()

# Hours contributed by each participant by group
ggplot(part_3, aes(PARTICIPANT, HOURS_COVERAGE, fill = group)) +
  geom_col()

# Hours contributed by each participant by group and half of month
ggplot(part_3, aes(PARTICIPANT, HOURS_COVERAGE, fill = group)) +
  geom_col() +
  facet_wrap(~half)
```

```{r Mixed Effects Models}
# random: Participant
# fixed: group, half
# There could be some correlation where past behavior may influence future behavior so
# ambulation and upright behavior may not be independent

ggplot(part_3_agg, aes(half, y = mean_upright, color = PARTICIPANT)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun= mean, geom = "line", aes(group = PARTICIPANT)) +
  labs(x = "Half", y = "Mean Upright", color = "Participant")
# No interaction

ggplot(part_3_agg, aes(half, y = mean_ambulation, color = PARTICIPANT)) +
  stat_summary(fun = mean, geom = "point") +
  stat_summary(fun= mean, geom = "line", aes(group = PARTICIPANT)) +
  labs(x = "Half", y = "Mean Ambulation", color = "Participant")
# No interaction

fit1 <- lmer(upright_prop ~ half + (1|PARTICIPANT), part_3, REML=F)
summary(fit1) 
# second half not significant compared to first half but small increase in upright

fit2 <- lmer(upright_prop ~ group + half + (1|PARTICIPANT), part_3, REML=F)
summary(fit2) 
# trt group is significant compared to ctrl, with being in the treatment group
# associated with a but 0.034979 decrease in upright
# second half not significant compared to first half but small increase in upright

fit3 <- lmer(ambulation_prop ~ half + (1|PARTICIPANT), part_3, REML=F)
summary(fit3)
# second half is not significant compared to first half but small non-significant 
# increase in ambulation

fit4 <- lmer(ambulation_prop ~ group + half + (1|PARTICIPANT), part_3, REML=F)
summary(fit4)
# trt group is not significant compared to crtl but less ambulation
# second half is non significant compared to first half

# ICC for participant variability
# ICC formula: the ICC is calculated as a ratio ICC = (variance of interest) / (total variance) = (variance of interest) / (variance of interest + unwanted variance)
    # Less than 0.50: Poor reliability
    # Between 0.5 and 0.75: Moderate reliability
    # Between 0.75 and 0.9: Good reliability
    # Greater than 0.9: Excellent reliability
fit1_var <- 0.000844/ (0.000844 + 0.000452) # result = 0.6512346 = Moderate reliability
fit2_var <- 0.0005367/ (0.0005367 + 0.0004520) # result = 0.542834 = Moderate reliability
fit3_var <- 0.0001077/ (0.0001077 + 0.0001510) # result = 0.4163123 = Poor reliability
fit4_var <- 0.0001054/ (0.0001054 + 0.0001510) # result = 0.4110764 = Poor reliability

# Likelihood test to see if group makes a difference
anova(fit1, fit2)
# group makes a difference with p-value of 0.02178

anova(fit3, fit4)
# group does not make a difference with p-value of 0.6254

fit5 <- lmer(upright_prop ~ group + (1|PARTICIPANT), part_3, REML=F)
fit6 <- lmer(ambulation_prop ~ group + (1|PARTICIPANT), part_3, REML=F)

anova(fit2, fit5) # half does not make a difference with a p-value of 0.6393
anova(fit4, fit6) # half does not make a difference with a p-value of 0.06341

```

``` {r Assumptions}
qqnorm(residuals(fit1)) # the data does not fall on the 45-degree reference line as well as I've seen before.
qqnorm(residuals(fit2)) # the data does not fall on the 45-degree reference line as well as I've seen before.
qqnorm(residuals(fit3)) # better normality with how the data falls on the 45-degree reference line.
qqnorm(residuals(fit4)) # better normality with how the data falls on the 45-degree reference line.


qqmath(ranef(fit1, condVar = TRUE), strip=FALSE)$PARTICIPANT # limited points but somewhat follows the reference line
qqmath(ranef(fit2, condVar = TRUE), strip=FALSE)$PARTICIPANT # limited points but somewhat follows the reference line

qqmath(ranef(fit3, condVar = TRUE), strip=FALSE)$PARTICIPANT # limited points but somewhat follows the reference line
qqmath(ranef(fit4, condVar = TRUE), strip=FALSE)$PARTICIPANT # limited points but somewhat follows the reference line
```


